function P = fan_presets()
%FAN_PRESETS 常见机箱风扇布局预设。每项：name、label、fans（{安装位 id, 类型, 型号} 列表）。
%   未列出的安装位为空。
    P = [ ...
        preset('balanced', '2 前进 · 后顶出（默认）', {'F2','intake','P12'; 'F3','intake','P12'; 'R1','exhaust','P12'; 'T1','exhaust','Stock120'}); ...
        preset('single_front', '1 前进 · 后顶出', {'F2','intake','P12'; 'R1','exhaust','P12'; 'T1','exhaust','Stock120'}); ...
        preset('front_rear', '前进后出', {'F2','intake','P12'; 'R1','exhaust','P12'}); ...
        preset('front_top', '前进顶出', {'F1','intake','P12'; 'F2','intake','P12'; 'T1','exhaust','P12'; 'T2','exhaust','P12'}); ...
        preset('bottom_top', '底进顶出', {'B1','intake','P12'; 'B2','intake','P12'; 'R1','exhaust','P12'; 'T1','exhaust','P12'; 'T2','exhaust','P12'}); ...
        preset('positive', '正压（3 进 1 出）', {'F1','intake','P12'; 'F2','intake','P12'; 'F3','intake','P12'; 'R1','exhaust','P12'}); ...
        preset('negative', '负压（1 进 3 出）', {'F2','intake','P12'; 'R1','exhaust','P12'; 'T1','exhaust','P12'; 'T2','exhaust','P12'}); ...
        preset('full', '全装（3 前进 · 后顶出 · 2 底进）', {'F1','intake','P12'; 'F2','intake','P12'; 'F3','intake','P12'; 'B1','intake','P12'; 'B2','intake','P12'; 'R1','exhaust','P12'; 'T1','exhaust','P12'; 'T2','exhaust','P12'})];
end

function p = preset(name, label, fans)
    p = struct('name', name, 'label', label, 'fans', {fans});
end
