function slots = fan_slots()
%FAN_SLOTS 机箱风扇安装位（400 mm 见方机箱）。
%   每个安装位：id、label、mount（front/top/rear/bottom）、alongMm（风扇中心沿壁坐标，
%   前/后壁为 y、顶/底壁为 x，相对机箱原点）。
%   前面板 3 个（上/中/下，中位正对显卡，下位跨电源仓挡板前缺口）、顶部 2 个、后部 1 个、
%   底部 2 个（电源前方，向电源仓送风；400 mm 机箱放不下两台并排的 120 mm 风扇，2D 简化为重叠 12 mm）。
    slots = [ ...
        slot('F1', '前上', 'front', 100); ...
        slot('F2', '前中', 'front', 220); ...
        slot('F3', '前下', 'front', 338); ...
        slot('T1', '顶后', 'top',   140); ...
        slot('T2', '顶前', 'top',   260); ...
        slot('R1', '后部', 'rear',  124); ...
        slot('B1', '底中', 'bottom', 230); ...
        slot('B2', '底前', 'bottom', 338)];
end

function s = slot(id, label, mount, alongMm)
    s = struct('id', id, 'label', label, 'mount', mount, 'alongMm', alongMm);
end
